# Generated by Django 6.0.4 on 2026-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='mock_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing')], default='reading', max_length=20),
        ),
    ]
