# Generated by Django 6.0.4 on 2026-05-16 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0002_mocktest_mock_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingpassage',
            name='mock',
        ),
        migrations.CreateModel(
            name='ReadingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_parts', to='mock.mocktest')),
            ],
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='mock.readingpart'),
            preserve_default=False,
        ),
    ]
