# Generated by Django 6.0.4 on 2026-05-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0003_remove_readingpassage_mock_readingpart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_parts', to='mock.mocktest')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Answer'), ('multiple', 'Multiple Choice'), ('true_false', 'TRUE / FALSE / NOT GIVEN')], default='text', max_length=20)),
                ('correct_answer', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mock.listeningpart')),
            ],
        ),
    ]
