# Generated by Django 6.0.4 on 2026-05-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0004_listeningpart_listeningquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('multiple', 'Multiple Choice A/B/C'), ('true_false', 'TRUE / FALSE / NOT GIVEN'), ('matching', 'Matching'), ('map_labeling', 'Map / Diagram Labeling'), ('sentence_completion', 'Sentence Completion'), ('note_completion', 'Note Completion'), ('table_completion', 'Table Completion')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('multiple', 'Multiple Choice A/B/C'), ('true_false', 'TRUE / FALSE / NOT GIVEN'), ('matching', 'Matching'), ('map_labeling', 'Map / Diagram Labeling'), ('sentence_completion', 'Sentence Completion'), ('note_completion', 'Note Completion'), ('table_completion', 'Table Completion')], default='text', max_length=30),
        ),
    ]
