# Generated by Django 6.0.4 on 2026-05-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0005_alter_listeningquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningpart',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='listening_audio/'),
        ),
    ]
