# Generated by Django 6.0.4 on 2026-06-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0006_listeningpart_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningpart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listening_images/'),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text / Completion'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('dropdown', 'Matching / Dropdown'), ('map_dropdown', 'Map / Diagram Dropdown'), ('table_completion', 'Table Completion')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('true_false', 'TRUE / FALSE / NOT GIVEN'), ('matching', 'Matching'), ('sentence_completion', 'Sentence Completion'), ('note_completion', 'Note Completion'), ('table_completion', 'Table Completion')], default='text', max_length=30),
        ),
        migrations.CreateModel(
            name='ListeningQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mock.listeningquestion')),
            ],
        ),
    ]
