# Generated by Django 6.0.4 on 2026-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0007_listeningpart_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text / Completion'), ('inline_completion', 'Inline Completion'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('dropdown', 'Matching / Dropdown'), ('map_dropdown', 'Map / Diagram Dropdown'), ('table_completion', 'Table Completion'), ('table_dropdown', 'Table Dropdown Matching')], default='text', max_length=30),
        ),
    ]
