# Generated by Django 6.0.4 on 2026-06-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0009_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], default='task1', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing_images/')),
                ('minimum_words', models.PositiveIntegerField(default=150)),
                ('order', models.PositiveIntegerField(default=1)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='mock.mocktest')),
            ],
        ),
    ]
