# Generated by Django 6.0.4 on 2026-06-04 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0010_writingtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1_answer', models.TextField(blank=True)),
                ('task2_answer', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('task1_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task2_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='mock.mocktest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
