# Generated by Django 6.0.4 on 2026-06-06 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0011_writingsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='writingsubmission',
            unique_together={('student', 'mock')},
        ),
    ]
