# Generated by Django 6.0.4 on 2026-06-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0012_alter_writingsubmission_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order', 'label']},
        ),
        migrations.AlterModelOptions(
            name='listeningpart',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='listeningquestion',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='listeningquestionchoice',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='readingpart',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='readingpassage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='writingtask',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='choice',
            name='label',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='paragraph_ref',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='word_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('match_heading', 'Matching Headings'), ('match_feature', 'Matching Features / People'), ('match_info', 'Matching Information'), ('match_ending', 'Matching Sentence Endings'), ('mcq_single', 'MCQ Single Answer'), ('mcq_multi', 'MCQ Multiple Answers'), ('sentence_complete', 'Sentence Completion'), ('summary_complete', 'Summary / Note / Table Completion'), ('short_answer', 'Short Answer Questions')], default='tfng', max_length=30),
        ),
        migrations.AlterField(
            model_name='readingpassage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ReadingQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('instruction', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('match_heading', 'Matching Headings'), ('match_feature', 'Matching Features / People'), ('match_info', 'Matching Information'), ('match_ending', 'Matching Sentence Endings'), ('mcq_single', 'MCQ Single Answer'), ('mcq_multi', 'MCQ Multiple Answers'), ('sentence_complete', 'Sentence Completion'), ('summary_complete', 'Summary / Note / Table Completion'), ('short_answer', 'Short Answer Questions')], default='tfng', max_length=30)),
                ('start_number', models.PositiveIntegerField(default=1)),
                ('end_number', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='mock.readingpart')),
            ],
            options={
                'ordering': ['part__order', 'order', 'start_number'],
            },
        ),
        migrations.CreateModel(
            name='ReadingGroupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mock.readingquestiongroup')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='mock.readingquestiongroup'),
        ),
    ]
