# Generated by Django 6.0.4 on 2026-06-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0013_alter_choice_options_alter_listeningpart_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='paragraph_ref',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='word_limit',
        ),
        migrations.AddField(
            model_name='readingquestiongroup',
            name='option_title',
            field=models.CharField(blank=True, help_text='Masalan: List of Headings, List of People, Paragraphs A-I', max_length=255),
        ),
        migrations.AddField(
            model_name='readingquestiongroup',
            name='word_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Completion yoki short answer uchun', null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mock.readingquestiongroup'),
        ),
        migrations.AlterField(
            model_name='readinggroupoption',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='readinggroupoption',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingquestiongroup',
            name='question_type',
            field=models.CharField(choices=[('paragraph_matching', 'Paragraph Matching'), ('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('matching_headings', 'Matching Headings'), ('matching_people', 'Matching People / Features'), ('matching_information', 'Matching Information'), ('matching_endings', 'Matching Sentence Endings'), ('mcq_single', 'Multiple Choice Single'), ('mcq_multi', 'Multiple Choice Multiple'), ('summary_completion', 'Summary / Note / Table Completion'), ('sentence_completion', 'Sentence Completion'), ('short_answer', 'Short Answer / Fill in the Blank')], default='tfng', max_length=40),
        ),
    ]
