# Generated by Django 6.0.4 on 2026-06-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0014_remove_question_paragraph_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpart',
            name='end_number',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AddField(
            model_name='readingpart',
            name='start_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
