# Generated by Django 6.0.4 on 2026-04-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_homeworkstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkstatus',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkstatus',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
