# Generated by Django 6.0.4 on 2026-05-05 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_studentclass_unique_active_student_per_class'),
        ('tracking', '0004_homeworkstatus_comment_homeworkstatus_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelOptions(
            name='homeworkstatus',
            options={'ordering': ['-checked_at']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'classroom', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='homeworkstatus',
            unique_together={('homework', 'student')},
        ),
    ]
