# Generated by Django 6.0.4 on 2026-05-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_attendance_options_alter_homework_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
