# Generated by Django 6.0.4 on 2026-04-30 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentclass_left_at_studentclass_removed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentclass',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'classroom'), name='unique_active_student_per_class'),
        ),
    ]
