# Generated by Django 6.0.4 on 2026-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_studentclass_unique_active_student_per_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='monthly_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
